shield.policy.password.min-length=7
shield.policy.password.max-length=10
shield.policy.date.allow-future-dates=true
shield.policy.date.allow-past-dates=true
shield.policy.register.username.min-length=5
shield.policy.register.username.max-length=15
shield.policy.register.email.required=false
shield.policy.register.phone.required=false
shield.policy.register.postregistermailtrigger=true
shield.policy.register.emailconfirmation.required=true
shield.policy.register.captcha.required=true
shield.policy.session.timeout-minutes=30